spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# auth routes - NO JWT filter!
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# admin routes - JWT filter!
spring.cloud.gateway.routes[1].id=admin-service
spring.cloud.gateway.routes[1].uri=lb://admin-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/admin/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthFilter

# employee routes - JWT filter!
spring.cloud.gateway.routes[2].id=employee-service
spring.cloud.gateway.routes[2].uri=lb://employee-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/employee/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthFilter

# manager routes - JWT filter!
spring.cloud.gateway.routes[3].id=manager-service
spring.cloud.gateway.routes[3].uri=lb://manager-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/manager/**
spring.cloud.gateway.routes[3].filters[0]=JwtAuthFilter

# csm routes - JWT filter!
spring.cloud.gateway.routes[4].id=csm-service
spring.cloud.gateway.routes[4].uri=lb://csm-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/csm/**
spring.cloud.gateway.routes[4].filters[0]=JwtAuthFilter

# learning routes - JWT filter!
spring.cloud.gateway.routes[5].id=learning-service
spring.cloud.gateway.routes[5].uri=lb://learning-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/learning/**
spring.cloud.gateway.routes[5].filters[0]=JwtAuthFilter

# certificate routes - JWT filter!
spring.cloud.gateway.routes[6].id=certificate-service
spring.cloud.gateway.routes[6].uri=lb://certificate-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/certificate/**
spring.cloud.gateway.routes[6].filters[0]=JwtAuthFilter

# report routes - JWT filter!
spring.cloud.gateway.routes[7].id=report-service
spring.cloud.gateway.routes[7].uri=lb://report-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/report/**
spring.cloud.gateway.routes[7].filters[0]=JwtAuthFilter

# notification routes - JWT filter!
spring.cloud.gateway.routes[8].id=notification-service
spring.cloud.gateway.routes[8].uri=lb://notification-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/notification/**
spring.cloud.gateway.routes[8].filters[0]=JwtAuthFilter

# audit routes - JWT filter!
spring.cloud.gateway.routes[9].id=audit-service
spring.cloud.gateway.routes[9].uri=lb://audit-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/audit/**
spring.cloud.gateway.routes[9].filters[0]=JwtAuthFilter

jwt.secret=mySecretKeyForJWTTokenGenerationLearningPortal2024
